# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mutant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000)),
                ('bot', models.CharField(max_length=200)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Answer')),
                ('expected_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mutant',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Strategy'),
        ),
        migrations.AddField(
            model_name='mutant',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Utterance'),
        ),
        migrations.AddField(
            model_name='mutant',
            name='validation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Validation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Entity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Intent'),
        ),
    ]
