# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='entity',
        ),
        migrations.AddField(
            model_name='answer',
            name='entity',
            field=models.ManyToManyField(to='framework.Entity'),
        ),
    ]
