# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0002_auto_20170622_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='entity',
            field=models.ManyToManyField(blank=True, null=True, to='framework.Entity'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.Intent'),
        ),
        migrations.AlterField(
            model_name='mutant',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.Answer'),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.Answer'),
        ),
        migrations.AlterField(
            model_name='utterance',
            name='expected_intent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='framework.Intent'),
        ),
    ]
