# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0003_auto_20170622_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utterance',
            name='bot',
        ),
    ]
