# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0004_remove_utterance_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='entity',
            field=models.ManyToManyField(blank=True, to='framework.Entity'),
        ),
    ]
