# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0006_auto_20170629_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='expected_intent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='framework.Intent'),
        ),
    ]
