# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '0007_auto_20170629_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homophone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('homophone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='framework.Homophone')),
            ],
        ),
    ]
